version: "3.4"
services:
  lidarr-24:
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr-24
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - LAN_NETWORK=172.18.0.0/24
    volumes:
      - /opt/appdata/lidarr-24/lidarr:/config
      - /mnt/tcrypt/music-24bit:/music-24bit
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/appdata/lidarr-24/90-config:/etc/cont-init.d/90-config
      - /etc/localtime:/etc/localtime:ro
    labels:
          traefik.enable: 'true'
          traefik.port: '8448'
          traefik.frontend.rule: 'Host:lidarr-24.pontiuspius-gce.duckdns.org'
          traefik.frontend.headers.SSLHost: 'pontiuspius-gce.duckdns.org'
          traefik.frontend.headers.SSLRedirect: 'true'
          traefik.frontend.headers.STSIncludeSubdomains: 'true'
          traefik.frontend.headers.STSPreload: 'true'
          traefik.frontend.headers.STSSeconds: '315360000'
          traefik.frontend.headers.browserXSSFilter: 'true'
          traefik.frontend.headers.contentTypeNosniff: 'true'
          traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
          traefik.frontend.headers.forceSTSHeader: 'true'
    ports:
      - 8448:8448
    restart: unless-stopped

  beets-24:
    container_name: beets-24
    image: linuxserver/beets:latest
    depends_on:
        - lidarr-24
    environment:
        - PUID=1000
        - PGID=1000
    volumes:
          - /opt/appdata/lidarr-24/beets:/config
          - /etc/localtime:/etc/localtime:ro
          - /mnt/tcrypt/music-24:/music-24
          - /mnt/tcrypt/downloads/music-24:/downloads
          - /dmx/completed:/dmx
    restart: unless-stopped

networks:
  default:
    external:
      name: plexguide
          aliases:
              - lidarr-24